import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Header/Header";

const PoppinsFont = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.className} antialiased`}
      >
        <Header/>
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
